name: UBERIVER
favicon: null
layout_spectrum: 0.12974
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c0e0d'
    - '#767776'
    - '#a19ca0'
    - '#cbcbcb'
  brandStrength: 0.3006112619768828
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
